version: '3'

services:

  core:
    container_name: core
    image: ${REPO}/radshift-core
    depends_on:
      - mongodb
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/home/pirate/conf:/usr/src/conf"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - CONF_DIR=/usr/src/conf
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=core
    networks:
      - www
      - internal

  # testapp:
  #   container_name: testapp
  #   image: radyak/radshift-testapp
  #   restart: on-failure
  #   environment:
  #     - PORT=3210
  #   networks:
  #     - internal
  
  mongodb:
    container_name: mongodb
    image: ${REPO}/radshift-mongodb
    restart: on-failure
    ports:
      - 27017
    networks:
      - internal

  radhub:
    container_name: radhub
    image: ${REPO}/radhub
    restart: on-failure
    environment:
      - PORT=4010
      - BACKENDS_FILE=/usr/src/radhub/radhub-backends.json
    volumes:
      - "/home/pirate:/usr/src/radhub"
    ports:
      - 4010:4010
    networks:
      - www
      - internal

  radshift-stream-downloader:
    container_name: radshift-stream-downloader
    image: ${REPO}/radshift-stream-downloader:latest
    restart: on-failure
    environment:
      - PORT=3009
    volumes:
      - "/home/pirate/output:/usr/src/app/output"
    ports:
      - 3009:3009
    networks:
      - www
      - internal


networks:

  www:
    driver: bridge

  internal:
    driver: bridge
    internal: true